### ISSUE TITLE
依赖的 overtrue/easy-sms 包已更新至2.0.4，望同步更新

### ISSUE THREAD

**Issue by remxcode** [yl/easysms-notification-channel#12]
因当前包使用overtrue/easy-sms的1.1版本在php8.1环境会报以下错误提示，望同步更新

`PHP Deprecated:  Return type of Overtrue\EasySms\PhoneNumber::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/vagrant/code/illusplus-server/vendor/overtrue/easy-sms/src/PhoneNumber.php on line 111
PHP Deprecated:  Return type of Overtrue\EasySms\Support\Config::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/vagrant/code/illusplus-server/vendor/overtrue/easy-sms/src/Support/Config.php on line 82
PHP Deprecated:  Return type of Overtrue\EasySms\Support\Config::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/vagrant/code/illusplus-server/vendor/overtrue/easy-sms/src/Support/Config.php on line 100
PHP Deprecated:  Return type of Overtrue\EasySms\Support\Config::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/vagrant/code/illusplus-server/vendor/overtrue/easy-sms/src/Support/Config.php on line 119
PHP Deprecated:  Return type of Overtrue\EasySms\Support\Config::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/vagrant/code/illusplus-server/vendor/overtrue/easy-sms/src/Support/Config.php on line 137`

**Comment by yl** [comment]
已更新
https://packagist.org/packages/leonis/easysms-notification-channel#2.0.0
