### ISSUE TITLE
请问如何根据区号选择不同的平台呢?

### ISSUE THREAD

**Issue by aoeng** [yl/easysms-notification-channel#14]
比如阿里云国际是不支持发国内的,所以国内用的其他平台国际用阿里云

**Comment by yl** [comment]
这个插件只是对 easysms 进行包装以适配 laravel，并没有新增功能。
所以 easysms 不支持的功能，这个插件也不支持。
但是，你可以通过自定义驱动实现你想要的功能。
参考：https://github.com/yl/easysms-notification-channel/blob/8cd72db241f1546f400341cdc5eb5788230ac747/src/Gateways/WinicGateway.php#L39-L43
