### ISSUE TITLE
我发送了验证码 怎么去接受我发出的验证码code呢？

### ISSUE THREAD

**Issue by CherishNA** [yl/easysms-notification-channel#3]
消息方法实现
`    public function toEasySms($notifiable)
    {
        $code = str_pad(random_int(1, 9999), 4, 0, STR_PAD_LEFT);
        return (new EasySmsMessage())
            ->setTemplate(env('SMS_TEMPLATE'))
            ->setData(['code' => $code]);
    }`
发送验证码调用
` Notification::route(
                EasySmsChannel::class,
                new PhoneNumber($phone,86)
            )->notify(new SmsVerificationCode());`
问题来了 我怎么获取消息方法里面的code啊。。或者我怎么把发送验证码时候的phone传进去

**Comment by fangmuke** [comment]
验证码可以通过构造函数传入。手机号见README.md

**Comment by CherishNA** [comment]
> 验证码可以通过构造函数传入。手机号见README.md

好的谢谢啦
