### ISSUE TITLE
怎么捕捉异常

### ISSUE THREAD

**Issue by yizenghui** [yl/easysms-notification-channel#4]
没有正常捕捉到异常信息，重现方式，输入错误的模版或者把签名类型设置为 验证码。
短信通知类型代码如下：

    public function via($notifiable)
    {
        return ['database', EasySmsChannel::class];
    }

    public function toEasySms($notifiable)
    {
        try{
            return (new EasySmsMessage)
            ->setContent('您提交的企业“123456”认证信息已通过审核，感谢您的使用。')
            ->setTemplate( 'SMS_198920278' ) // 短信阿里云模板
            ->setData(['company_name' => 2222222]);
        } catch (\Overtrue\EasySms\Exceptions\NoGatewayAvailableException $e) {
            dd($e);
        }
    }

**Comment by yl** [comment]
https://github.com/yl/easysms-notification-channel/blob/e9fddac0853caad1baa2722ac29048208b72d51b/src/Channels/EasySmsChannel.php#L35-L39
