### ISSUE TITLE
errorlog 网关问题

### ISSUE THREAD

**Issue by nfhh** [yl/easysms-notification-channel#6]
![image](https://user-images.githubusercontent.com/30310521/98676072-120f6f00-2396-11eb-9046-0904b47df30f.png)
第一次发会这样

**Comment by yl** [comment]
你期望是怎样？请描述一下你的需求。

**Comment by nfhh** [comment]
> 你期望是怎样？请描述一下你的需求。

报错了 啥原因啊

**Comment by yl** [comment]
这不是报错，功能就是这样的，如果短信网关中开启了errorlog，就会在配置的日志文件中短信发送信息

**Comment by nfhh** [comment]
> 这不是报错，功能就是这样的，如果短信网关中开启了errorlog，就会在配置的日志文件中短信发送信息

恩 但是开启errorlog不是只有发生错误才记录吗？

**Comment by yl** [comment]
发送短信可以同时指定多个网关，会按顺序尝试发送短信，如果发送失败，会继续尝试，如果都失败才会报错。
errorlog 是一个特殊的网关，即：将短信发送信息记录到日志文件中，一旦记录成功后即视为短信发送成功（不报错），适合开发调试的时候使用。
建议到 [overtrue/easy-sms](https://github.com/overtrue/easy-sms) 查看详细使用说明。

**Comment by nfhh** [comment]
> 发送短信可以同时指定多个网关，会按顺序尝试发送短信，如果发送失败，会继续尝试，如果都失败才会报错。
> errorlog 是一个特殊的网关，即：将短信发送信息记录到日志文件中，一旦记录成功后即视为短信发送成功（不报错），适合开发调试的时候使用。
> 建议到 [overtrue/easy-sms](https://github.com/overtrue/easy-sms) 查看详细使用说明。

你的意思是 不管发没发送成功 只要开启了errorlog 都会记录到文件中？errorlog是为了本地开发用 线上不用开启？

**Comment by yl** [comment]
只有在其他网关发送失败的情况下，才会把要发送的短信记录的日志中。
不建议生产环境开启 errorlog 。

**Comment by nfhh** [comment]
> 只有在其他网关发送失败的情况下，才会把要发送的短信记录的日志中。
> 不建议生产环境开启 errorlog 。

厉害 谢谢老哥
