### ISSUE TITLE
老铁 可能你引入的"overtrue/easy-sms": "^1.1"版本太低了 报了PSR-4错

### ISSUE THREAD

**Issue by nfhh** [yl/easysms-notification-channel#8]
![image](https://user-images.githubusercontent.com/30310521/106684055-a76e7800-6600-11eb-938d-be431c5fe892.png)

老铁 可能你引入的"overtrue/easy-sms": "^1.1"版本太低了 报了PSR-4错
麻烦修下啊

**Comment by yl** [comment]
你好，这是 overtrue/easy-sms 包的错误导致的
https://github.com/overtrue/easy-sms/pull/284
虽然问题被修复，但是最新的release依然有问题

**Comment by nfhh** [comment]
> 你好，这是 overtrue/easy-sms 包的错误导致的
> [overtrue/easy-sms#284](https://github.com/overtrue/easy-sms/pull/284)
> 虽然问题被修复，但是最新的release依然有问题

https://github.com/overtrue/easy-sms/releases
最新的1.3.1还是有这问题吗？

**Comment by yl** [comment]
你直接运行
`composer require overtrue/easy-sms:1.3.1`
试一下就知道了
