### ISSUE TITLE
如何获取通知后的结果

### ISSUE THREAD

**Issue by amw0918** [yl/easysms-notification-channel#9]
使用阿里云短信服务，如何获取接口返回的结果
例如：是发送成功，还是账户余额不足等，错误代码或者原因，smslog.log 只呈现出来local.ERROR  message:"" 
我使用的laravel的版本是8.26.1

**Comment by yl** [comment]
建议查看源码
https://github.com/yl/easysms-notification-channel/blob/master/src/Channels/EasySmsChannel.php#L35-L39
